[email]
sender = "jtmorgan0513@gmail.com"
app_password = "nbzn alsq evco qdoo"
recipient = "tyler.morgan@transformco.com"

[replit]
REPLIT_DASHBOARD_URL = "https://byovdashboard.replit.app"
REPLIT_DASHBOARD_USERNAME = "admin"
REPLIT_DASHBOARD_PASSWORD = "admin123"
